name: Archive Weekly Report
on:
  workflow_dispatch: # This lets you run it manually with one click
  schedule:
    # This runs at 00:00 (Midnight) every Sunday UTC
    - cron: '0 0 * * 0'

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive and Reset
        run: |
          # Create archive folder if it doesn't exist
          mkdir -p archive
          
          # Get current date (Year-Month-Day)
          FILENAME="archive/gex-$(date +'%Y-%m-%d').html"
          
          # Copy current index to the archive folder
          cp index.html $FILENAME

          # Archive watch.html
          WATCH_FILENAME="archive/watch-$(date +'%Y-%m-%d').html"
          cp watch.html "$WATCH_FILENAME"

          INTRAWEEK_FILENAME="archive/intraweek-$(date +'%Y-%m-%d').html"
          cp intraweek.html "$INTRAWEEK_FILENAME"
          
          ## Optional: Clear index.html or replace with a "Coming Soon" template
          #echo "<h1>New Report Coming Soon</h1>" > index.html

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Automated archive for $(date +'%Y-%m-%d')"
          git push
